# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_glmreg_wrappers", use_symbols = TRUE, package_name = "glmreg")

#' @usage NULL
#' @useDynLib glmreg, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
glm_irls <- function(x, y) .Call(wrap__glm_irls, x, y)


# nolint end
